// Generated by https://quicktype.io

export interface SchedulerResponse {
    idSlot:           number;
    idExam:           number;
    nameExam:         string;
    startSlot:        string;
    timeSlot:         string;
    durationSlot:     number;
    nameProfessional: string;
    endSlot:          string;
}

