name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major"
        minor_patttern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
      
    - name: Create BuildX
      run: |
        docker buildx create --name mybuilder --driver docker-container --bootstrap --use
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t saludintegraldev/backend:$NEW_VERSION .
        docker buildx build --platform linux/amd64,linux/arm64 -t saludintegraldev/backend:latest .
#        docker build -t saludintegraldev/backend:$NEW_VERSION .
#        docker build -t saludintegraldev/backend .
    
    - name: Push docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push saludintegraldev/backend:$NEW_VERSION
        docker push saludintegraldev/backend:latest
