name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "login start"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "login end"
        
    - name: Build docker image
      run: |
        docker build -t saludintegraldev/backend:0.0.1 .
        docker build -t saludintegraldev/backend:latest .
    
    - name: Push docker image
      run: |
        docker push saludintegraldev/backend:0.0.1
        docker push saludintegraldev/backend:latest
